### ISSUE TITLE
problem in completion

### ISSUE THREAD

**Issue by kozo2** [SciRuby/iruby#102]
In pry on the terminal, this completion works
```
[1] pry(main)> "aaa".
Display all 160 possibilities? (y or n)
.__binding__                      .delete                           .hex                              .object_id                        .scrub                            .tap
.__id__                           .delete!                          .include?                         .oct                              .scrub!                           .to_c
.__send__                         .display                          .index                            .ord                              .send                             .to_enum
.ascii_only?                      .downcase                         .insert                           .partition                        .setbyte                          .to_f
.b                                .downcase!                        .inspect                          .prepend                          .shellescape                      .to_i
.between?                         .dump                             .instance_eval                    .pretty_inspect                   .shellsplit                       .to_r
.bytes                            .dup                              .instance_exec                    .pretty_print                     .singleton_class                  .to_s
.bytesize                         .each_byte                        .instance_of?                     .pretty_print_cycle               .singleton_method                 .to_str
.byteslice                        .each_char                        .instance_variable_defined?       .pretty_print_inspect             .singleton_methods                .to_sym
.capitalize                       .each_codepoint                   .instance_variable_get            .pretty_print_instance_variables  .size                             .tr
.capitalize!                      .each_line                        .instance_variable_set            .private_methods                  .slice                            .tr!
.casecmp                          .empty?                           .instance_variables               .protected_methods                .slice!                           .tr_s
.center                           .encode                           .intern                           .pry                              .split                            .tr_s!
.chars                            .encode!                          .is_a?                            .public_method                    .squeeze                          .trust
.chomp                            .encoding                         .itself                           .public_methods                   .squeeze!                         .unicode_normalize
.chomp!                           .end_with?                        .kind_of?                         .public_send                      .start_with?                      .unicode_normalize!
.chop                             .enum_for                         .length                           .remove_instance_variable         .strip                            .unicode_normalized?
.chop!                            .eql?                             .lines                            .replace                          .strip!                           .unpack
.chr                              .equal?                           .ljust                            .respond_to?                      .sub                              .untaint
.class                            .extend                           .lstrip                           .reverse                          .sub!                             .untrust
.clear                            .force_encoding                   .lstrip!                          .reverse!                         .succ                             .untrusted?
.clone                            .freeze                           .match                            .rindex                           .succ!                            .upcase
.codepoints                       .frozen?                          .method                           .rjust                            .sum                              .upcase!
.concat                           .getbyte                          .methods                          .rpartition                       .swapcase                         .upto
.count                            .gsub                             .next                             .rstrip                           .swapcase!                        .valid_encoding?
.crypt                            .gsub!                            .next!                            .rstrip!                          .taint                            
.define_singleton_method          .hash                             .nil?                             .scan                             .tainted?
```
but this completion does not work on IRuby Notebook.

I checked this on
- IRuby 0.2.9
- Ruby 2.3.1
- rbenv 1.0.0
- Mac OSX 10.11.6

**Comment by kozo2** [comment]
When I tried this completion, the follwing output was printed on the server-side
```
WARN -- : Inspection error: wrong number of arguments (1 for 2)
/var/lib/gems/2.1.0/gems/iruby-0.2.9/lib/iruby/backend.rb:6:in `eval'
/var/lib/gems/2.1.0/gems/iruby-0.2.9/lib/iruby/kernel.rb:139:in `inspect_request'
/var/lib/gems/2.1.0/gems/iruby-0.2.9/lib/iruby/kernel.rb:47:in `dispatch'
/var/lib/gems/2.1.0/gems/iruby-0.2.9/lib/iruby/kernel.rb:37:in `run'
/var/lib/gems/2.1.0/gems/iruby-0.2.9/lib/iruby/command.rb:70:in `run_kernel'
/var/lib/gems/2.1.0/gems/iruby-0.2.9/lib/iruby/command.rb:34:in `run'
/var/lib/gems/2.1.0/gems/iruby-0.2.9/bin/iruby:5:in `<top (required)>'
/usr/local/bin/iruby:23:in `load'
/usr/local/bin/iruby:23:in `<main>'
```
