### ISSUE TITLE
iruby console: ERROR Failed to run command

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/iruby#116]
Hi all,

Just reinstalled iruby, and I can't start the console.

```
 iruby console
Could not load bundler: Could not locate Gemfile or .bundle/ directory
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
[ZMQTerminalIPythonApp] ERROR | Failed to run command:
[u'/Users/jwoods/.rbenv/versions/2.2.2/bin/iruby', u'kernel', u'/Users/jwoods/Library/Jupyter/runtime/kernel-74638.json']
    PATH='/Users/jwoods/.rbenv/versions/2.4.0/bin:/usr/local/Cellar/rbenv/1.1.0/libexec:/Users/jwoods/.rbenv/shims:/Users/jwoods/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/Library/TeX/texbin:/Users/jwoods/bin'
    with kwargs:
{'cwd': None, 'stdin': -1, 'preexec_fn': <function <lambda> at 0x103864050>, 'stderr': None, 'stdout': None}

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/usr/local/lib/python2.7/site-packages/jupyter_console/app.py", line 105, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I can start `iruby notebook`, but when I try to open a Ruby notebook, the only option I have is for 2.2.2 (which I uninstalled; I'm running only 2.4.0 via rbenv and my system version is 2.0.0p648).

What's going on?

**Comment by icm7216** [comment]
please try this

1.   change to your ruby version
```
$ rbenv global 2.4.0
```

2.   register ruby to the jupyter
```
$ iruby register --force
$ jupyter kernelspec install ~/.ipython/kernels/ruby
```

3.   start jupyter
```
$ jupyter notebook
```

**Comment by ckib16** [comment]
Also - found it useful to "purge" the cache of ruby kernels as listed here:
- http://stackoverflow.com/questions/31976367/how-do-i-delete-refresh-available-kernels-for-ipython-jupyter-notebook-v4-0

Be sure to get both folders:
- `/Users/${USER}/Library/Jupyter/kernels`
- `/usr/local/share/jupyter/kernels`

The correct kernel version loaded for me after that.

**Comment by v0dro** [comment]
@mohawkjohn has your problem been fixed?

**Comment by homonecloco** [comment]
I'm having the same issue, has anyone been able to solve it? In my case I have Jupiter installed with anaconda on Mac.

**Comment by kojix2** [comment]
@homonecloco

Please check already registered kernel and location.
```bash
jupyter kernelspec list
```
Maybe the old version of IRuby is located in some jupyter directory.
In that case, jupyter may not find the kernel you registered in `.ipython` directory. 
you need to install the kernel manually using `juypter kernelspec` command.

see the comment [icm7216](/icm7216) write above.
