### ISSUE TITLE
Preserve showing exception occurred in check_bundler when Gemfile is not available

### ISSUE THREAD

**Issue by mrkn** [SciRuby/iruby#144]
The following exception is too noisy.

```
W, [2018-03-23T11:34:57.092795 #36862]  WARN -- : Could not load bundler: Could not find coderay-1.1.1 in any of the sources
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:88:in `block in materialize'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:82:in `map!'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:82:in `materialize'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/lib/iruby/command.rb:109:in `check_bundler'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/lib/iruby/command.rb:67:in `run_kernel'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
/Users/mrkn/.rbenv/versions/2.5/bin/iruby:23:in `load'
/Users/mrkn/.rbenv/versions/2.5/bin/iruby:23:in `<main>'
```

**Comment by kojix2** [comment]
Maybe #201 solved this issue, I think...
Please reopen and let me know if there is anything that concerns you.
