### ISSUE TITLE
 Windows - Kernel died: uninitialized constant IRuby::Kernel::Session 

### ISSUE THREAD

**Issue by jmarrec** [SciRuby/iruby#148]
## Error

I did see issue #74 prior to posting this one, but I am **not** in a project with a gemfile.

I'm getting the following error:

```
[I 08:24:56.765 NotebookApp] Creating new notebook in /Downloads
[I 08:24:57.343 NotebookApp] Kernel started: 0cdf8b6c-668e-43d4-82cd-d0e739a5d38a
[W 08:24:57.424 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180417082447 (::1) 7.50ms referer=http://localhost:8888/notebooks/Downloads/Untitled1.ipynb?kernel_name=ruby
W, [2018-04-17T08:24:57.646037 #7488]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/bundler.rb:221:in `rescue in root'
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/bundler.rb:217:in `root'
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/bundler.rb:80:in `bundle_path'
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/bundler.rb:532:in `configure_gem_home'
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/bundler.rb:513:in `configure_gem_home_and_path'
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/bundler.rb:66:in `configure'
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/bundler.rb:134:in `definition'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:109:in `check_bundler'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:67:in `run_kernel'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
C:/Ruby22-x64/bin/iruby:23:in `load'
C:/Ruby22-x64/bin/iruby:23:in `<main>'

WARNING: ::CZMQ::FFI is not available without libczmq.

You should install cztop, rbczmq or ffi_rzmq before running iruby notebook. See README.
F, [2018-04-17T08:24:57.818037 #7488] FATAL -- : Kernel died: uninitialized constant IRuby::Kernel::Session
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/kernel.rb:18:in `initialize'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:70:in `new'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:70:in `run_kernel'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
C:/Ruby22-x64/bin/iruby:23:in `load'
C:/Ruby22-x64/bin/iruby:23:in `<main>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/kernel.rb:18:in `initialize': uninitialized constant IRuby::Kernel::Session (NameError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:70:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:70:in `run_kernel'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
        from C:/Ruby22-x64/bin/iruby:23:in `load'
        from C:/Ruby22-x64/bin/iruby:23:in `<main>'
[I 08:25:00.309 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
```

**What am I missing here please?**

**Short info on system:**

* Platform: Windows 10
* `jupyter --version`: 4.4.0
* `ruby --version`: ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

## Steps done to install

Commands I ran to update everything first, then install iRuby per instructions at https://github.com/SciRuby/iruby#windows

```
conda clean -tipsy
conda update conda
conda update --all

gem update --system
gem update

gem install cztop
gem install iruby
iruby register --force
```

### `jupyter kernelspec list`:

```
> jupyter kernelspec list
Available kernels:
  ruby       C:\Users\julien\.ipython\kernels\ruby
  python3    C:\Miniconda3\share\jupyter\kernels\python3
```

### `conda env list`:

```
> conda env list
# packages in environment at C:\Miniconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.10           py36hcd07829_0  
asn1crypto                0.24.0                   py36_0  
attrs                     17.4.0                    <pip>
babel                     2.5.3                    py36_0  
backcall                  0.1.0                    py36_0  
beautifulsoup4            4.6.0            py36hd4cc5e8_1  
bleach                    2.1.3                    py36_0  
ca-certificates           2018.03.07                    0  
certifi                   2018.1.18                py36_0  
cffi                      1.11.5           py36h945400d_0  
chardet                   3.0.4            py36h420ce6e_1  
colorama                  0.3.9            py36h029ae33_0  
colorlover                0.2.1                     <pip>
conda                     4.5.1                    py36_0  
conda-env                 2.6.0                h36134e3_1  
console_shortcut          0.1.1                h6bb2dd7_3  
cryptography              2.2.2            py36hfa6e2cd_0  
cufflinks                 0.12.1                    <pip>
cycler                    0.10.0           py36h009560c_0  
decorator                 4.3.0                    py36_0  
df2gspread                0.2.3                    py36_0    conda-forge
docopt                    0.6.2                    py36_0  
docutils                  0.14             py36h6012d8f_0  
entrypoints               0.2.3            py36hfd66bb0_2  
eppy                      0.5.46                    <pip>
et_xmlfile                1.0.1            py36h3d2d736_0  
fix-yahoo-finance         0.0.21                    <pip>
freetype                  2.8                  h51f8f2c_1  
google-api-python-client  1.6.4                      py_0    conda-forge
gspread                   0.6.2                    py36_0    conda-forge
html5lib                  1.0.1            py36h047fa9f_0  
httplib2                  0.11.1                   py36_0    conda-forge
icc_rt                    2017.0.4             h97af966_0  
icu                       58.2                 ha66f8fd_1  
idna                      2.6              py36h148d497_1  
imagesize                 1.0.0                    py36_0  
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py36_0  
ipython                   6.3.1                    py36_0  
ipython_genutils          0.2.0            py36h3c5d0ee_0  
ipywidgets                7.2.1                    py36_0  
jdcal                     1.4                      py36_0  
jedi                      0.11.1                   py36_1  
jinja2                    2.10             py36h292fed1_0  
jpeg                      9b                   hb83a4c4_2  
jsonschema                2.6.0            py36h7636477_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36h6d89b47_1  
jupyter_contrib_core      0.3.3                    py36_1    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py36_0    conda-forge
jupyter_core              4.4.0            py36h56e9d50_0  
jupyter_highlight_selected_word 0.1.1                    py36_0    conda-forge
jupyter_latex_envs        1.4.4                    py36_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py36_0    conda-forge
kiwisolver                1.0.1            py36h12c3424_0  
libiconv                  1.15                 h1df5818_7  
libpng                    1.6.34               h79bbb47_0  
libxml2                   2.9.8                hc33b523_0  
libxslt                   1.1.32               hf6f1972_0  
lunardate                 0.1.5                     <pip>
lxml                      4.2.1            py36heafd4d3_0  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markupsafe                1.0              py36h0e26971_1  
matplotlib                2.2.2            py36h153e9ff_1  
menuinst                  1.4.11           py36hfa6e2cd_0  
mistune                   0.8.3                    py36_0  
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py36h452e1ab_0  
mkl_random                1.0.1            py36h9258bd6_0  
more-itertools            4.1.0                     <pip>
msys2-conda-epoch         20160418                      1  
multitasking              0.0.6                     <pip>
munch                     2.2.0                     <pip>
nbconvert                 5.3.1            py36h8dc0fde_0  
nbformat                  4.4.0            py36h3a5bc1b_0  
notebook                  5.4.1                    py36_0  
numpy                     1.14.2           py36h5c71026_1  
numpydoc                  0.8.0                    py36_0  
oauth2client              4.1.2                    py36_0    conda-forge
openpyxl                  2.5.2                    py36_0  
openssl                   1.0.2o               h8ea7d77_0  
packaging                 17.1                     py36_0  
pandas                    0.22.0           py36h6538335_0  
pandas-datareader         0.6.0                    py36_0  
pandoc                    1.19.2.1             hb2460c7_1  
pandocfilters             1.4.2            py36h3ef6317_1  
parso                     0.1.1            py36hae3edee_0  
patsy                     0.5.0                    py36_0  
pickleshare               0.7.4            py36h9de030f_0  
pip                       9.0.3                    py36_0  
plotly                    2.5.1                    py36_0  
pluggy                    0.6.0                     <pip>
prompt_toolkit            1.0.15           py36h60b8f86_0  
pulp                      1.6.8                    py36_0    conda-forge
py                        1.5.3                     <pip>
pyasn1                    0.4.2            py36h22e697c_0  
pyasn1-modules            0.2.1            py36hd1453cb_0  
pycosat                   0.6.3            py36h413d8a4_0  
pycparser                 2.18             py36hd053e01_1  
pycrypto                  2.6.1            py36hfa6e2cd_7  
pydot3k                   1.0.17                    <pip>
pygments                  2.2.0            py36hb010967_0  
pyopenssl                 17.5.0           py36h5b7d817_0  
pyparsing                 2.2.0            py36h785a196_1  
pyqt                      5.9.2            py36h1aa27d4_0  
pysocks                   1.6.8                    py36_0  
pytest                    3.5.0                     <pip>
python                    3.6.5                h0c2934d_0  
python-dateutil           2.7.2                    py36_0  
pytz                      2018.4                   py36_0  
pywin32                   223              py36hfa6e2cd_0  
pywinpty                  0.5.1                    py36_0  
pyyaml                    3.12             py36h1d1928f_1  
pyzmq                     17.0.0           py36hfa6e2cd_0  
qt                        5.9.4            vc14hd9fb3db_0  
qtconsole                 4.3.1            py36h99a29a9_0  
requests                  2.18.4           py36h4371aae_1  
requests-file             1.4.1                    py36_0  
requests-ftp              0.3.1                    py36_0  
rsa                       3.4.2                    py36_0    conda-forge
ruamel_yaml               0.15.35          py36hfa6e2cd_1  
scikit-learn              0.19.1           py36h53aea1b_0  
scipy                     1.0.1            py36hce232c7_0  
seaborn                   0.8.1            py36h9b69545_0  
send2trash                1.5.0                    py36_0  
setuptools                39.0.1                   py36_0  
simplegeneric             0.8.1                    py36_2  
simplejson                3.13.2                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.11.0           py36h4db2310_1  
snowballstemmer           1.2.1            py36h763602f_0  
sphinx                    1.7.2                    py36_0  
sphinxcontrib             1.0              py36hbbac3d2_1  
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1  
sqlite                    3.22.0               h9d3ae62_0  
statsmodels               0.8.0            py36h6189b4c_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h2698cfe_0  
tinynumpy                 1.2.1                     <pip>
tornado                   5.0.1                    py36_1  
tqdm                      4.19.9                   py36_0  
traitlets                 4.3.2            py36h096827d_0  
typing                    3.6.4                    py36_0  
uritemplate               3.0.0                    py36_0    conda-forge
urllib3                   1.22             py36h276f60a_0  
vc                        14                   h0510ff6_3  
vs2015_runtime            14.0.25123                    3  
wcwidth                   0.1.7            py36h3d5aa90_0  
webencodings              0.5.1            py36h67c50ae_1  
wheel                     0.31.0                   py36_0  
widgetsnbextension        3.2.0                    py36_0  
win_inet_pton             1.0.1            py36he67d7fd_1  
wincertstore              0.2              py36h7fe50ca_0  
winpty                    0.4.3                         4  
wrapt                     1.10.11          py36he5f5981_0  
xlsxwriter                1.0.4                    py36_0  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h8395fce_2  

```

### `gem list`:

```
> gem list
bigdecimal (1.3.4, default: 1.2.6)
bond (0.5.1)
bundler (default: 1.16.1)
coderay (1.1.2)
czmq-ffi-gen (0.15.0)
cztop (0.13.1)
data_uri (0.1.0)
ffi (1.9.23 x64-mingw32)
io-console (0.4.6, default: 0.4.3)
iruby (0.3)
json (2.1.0, default: 1.8.1)
method_source (0.9.0)
mimemagic (0.3.2)
mini_portile2 (2.3.0)
minitest (5.11.3, 5.4.3)
multi_json (1.13.1)
nokogiri (1.8.2 x64-mingw32)
os (1.0.0)
power_assert (1.1.1, 0.2.2)
pry (0.11.3)
pry-doc (0.13.4)
pry-theme (1.2.0)
psych (3.0.2 x64-mingw32, default: 2.0.8)
rake (12.3.1, default: 10.4.2)
rdoc (6.0.3, default: 4.2.0)
roo (2.7.1)
rubygems-update (2.7.6)
rubyXL (3.3.29)
rubyzip (1.2.1)
test-unit (3.2.7, 3.0.8)
yard (0.9.12)
```

**Comment by jmarrec** [comment]
Hum interestingly enough, digging a bit I think something is wrong with my install of cztop, seems like it's looking for Unix paths to DLLs.

```
[1] > require 'cztop'

WARNING: ::CZMQ::FFI is not available without libczmq.

LoadError: Could not open library '/usr/local/lib/libzmq.dll': The specified module could not be found.
.
Could not open library '/opt/local/lib/libzmq.dll': The specified module could not be found.
.
Could not open library '/usr/lib64/libzmq.dll': The specified module could not be found.
.
Could not open library 'libzmq': The specified module could not be found.
.
Could not open library 'libzmq.dll': The specified module could not be found.
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.23-x64-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib'
```

**Comment by jmarrec** [comment]
I uninstalled cztop 0.13.1 and specifically reinstalled cztop 0.12.2 (I found a machine where iRuby was working and found this specific version), and now it works just fine. I guess this is a cztop issue and not an iRuby one, so closing.

```
gem uninstall cztop
gem uninstall czmq-ffi-gen
gem uninstall iruby
gem uninstall ffi
gem install cztop -v 0.12.2
gem install iruby
```

**Comment by ratfinkz** [comment]
did this ever work in Windows ?
there seems to be hundreds of issues trying to run ruby/iruby with jupyter
the instructions are vague at best

**Comment by kojix2** [comment]
Hello @ratfinkz 
IRuby should work on Windows, although it is not well maintained. If it doesn't, please create a new issue and ask questions.
