### ISSUE TITLE
Test suite hangs with Ruby 3.4

### ISSUE THREAD

**Issue by simpl1g** [SciRuby/iruby#357]
It's continuation of this PR https://github.com/SciRuby/iruby/pull/356

Currently Ruby process can't finish after all tests passed. I've dumped all thread backtraces and it shows
```
/Users/simpl1g/.rbenv/versions/3.4.0-preview2/lib/ruby/gems/3.4.0+0/gems/ffi-rzmq-2.0.7/lib/ffi-rzmq/device.rb:24:in 'LibZMQ.zmq_proxy'
/Users/simpl1g/.rbenv/versions/3.4.0-preview2/lib/ruby/gems/3.4.0+0/gems/ffi-rzmq-2.0.7/lib/ffi-rzmq/device.rb:24:in 'ZMQ::Device#initialize'
/Users/simpl1g/work/ruby_projects/iruby/lib/iruby/session_adapter/ffirzmq_adapter.rb:29:in 'Class#new'
/Users/simpl1g/work/ruby_projects/iruby/lib/iruby/session_adapter/ffirzmq_adapter.rb:29:in 'IRuby::SessionAdapter::FfirzmqAdapter#heartbeat_loop'
/Users/simpl1g/work/ruby_projects/iruby/lib/iruby/session.rb:55:in 'block in IRuby::Session#setup_heartbeat'
```

So it looks like a problem in `ffi-rzmq` gem. If I comment out creating heartbeat thread all tests passes and process completes fine. But I'm not sure that this is correct way to do this :)

**Comment by kojix2** [comment]
Ruby committer @tompng looked into this issue on slack-jp and found that the problem is most likely related to ffi-rzmq. Thanks tompng!

![Image](https://github.com/user-attachments/assets/fa143b94-1240-4f5f-8a79-2225d58efc5e)

Here is the English translation of the text in the image ( ChatGPT) :

---

### **koji×2 (January 25, 19:40)**  
This might not be the right place to ask, but in Ruby 3.4, when running tests in IRuby (the Jupyter Notebook Ruby kernel), the tests seem to pass, yet they still fail due to a timeout. Does anyone have any ideas?  

[[GitHub Actions link](https://github.com/SciRuby/iruby/actions/runs/12941938897/job/36098818328)](https://github.com/SciRuby/iruby/actions/runs/12941938897/job/36098818328)

---

### **tompng (January 25, 20:41)**  
That's a mystery.  

When setting `IRUBY_TEST_SESSION_ADAPTER_NAME=ffi-rzmq` and running  
- `session_test.rb` (only running `test_new_with_session_adapter`)  
- `run-test.rb`  

It seems to get stuck at this point:  
```ruby
exit Test::Unit::AutoRunner.run(true, test_dir)
```
It looks like `exit` is executed, but for some reason, it doesn't actually exit.

---

### **tompng (January 25, 21:18)**  
If you execute:  
```ruby
IRuby::Session.new(session_config, 'ffi-rzmq'); exit
```
the script never stops.  

It seems like `zmq_context` has a `terminate` method, but calling it does nothing, and it just waits indefinitely. I feel like executing `terminate` right before `exit` might resolve the issue.  

(However, I don't know if this behavior changes between versions 3.4 and 3.3.)

---

### **koji×2 (January 25, 21:38)**  
Thank you very much! That helps a lot!

---

### **tompng (January 25, 22:27)**  
At this point, I’ll step aside. Good luck.  

---

**Comment by kojix2** [comment]
According to GPT-5’s code review (with the bullet points re-organized by the human, kojix2)

## ZMQ::Device is the Cause

- Running `ZMQ::Device` causes the process to hang on exit.
- `ZMQ::Device` internally calls `libzmq`’s `zmq_proxy` in a blocking loop, and there is no stop API.
- Ruby 3.4 has stricter rules for handling other threads when the main thread exits.
- In Ruby 3.4, if blocking threads remain, the process does not terminate.
- It is necessary to explicitly close the socket or terminate the context.

## IRuby Uses ZMQ::Device for the Heartbeat

- In IRuby, the heartbeat mechanism relies on `ZMQ::Device`.
- Because it is referenced as a thread-local variable, the GC finalizer does not run.
  - Moreover, since the timing of GC/finalizers is unpredictable, they should not be relied upon.
- Applications that run `ZMQ::Device` inside a thread encounter hangs.
- It is necessary to explicitly call `socket.close` or `ctx.terminate`.

## GPT-5’s Recommended Solution

- For IRuby’s heartbeat, use a simple REP echo loop (`recv → send`) in a thread instead of `ZMQ::Device`, and on shutdown explicitly close the heartbeat socket (and, if necessary, call `ctx.terminate`).

**Comment by kojix2** [comment]
I believe this issue has been resolved in https://github.com/SciRuby/iruby/commit/ee7ffeabad00fa1582e04da04a511e037e71b8cd. I will close this ticket for now. Of course, there may still be undiscovered bugs, so please report them if you encounter any.

Thank you for your report.
We plan to release a new version of IRuby soon.

**Comment by simpl1g** [comment]
Thank you 🙇
