### ISSUE TITLE
Could not load bundler: Could not locate Gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by Leventhan** [SciRuby/iruby#45]
I tried installing iruby using RVM into my global gemset. Now, I'm getting the following error:

```
$ iruby
Could not load bundler: Could not locate Gemfile or .bundle/ directory
W, [2015-08-06T05:22:30.899010 #26154]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.4/lib/bundler.rb:198:in `rescue in root'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.4/lib/bundler.rb:194:in `root'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.4/lib/bundler.rb:101:in `bundle_path'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.4/lib/bundler.rb:420:in `configure_gem_home_and_path'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.4/lib/bundler.rb:92:in `configure'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.4/lib/bundler.rb:153:in `definition'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/iruby-0.2.7/lib/iruby/command.rb:109:in `check_bundler'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/iruby-0.2.7/lib/iruby/command.rb:67:in `run_kernel'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/iruby-0.2.7/lib/iruby/command.rb:34:in `run'
/Users/yosriady/.rvm/gems/ruby-2.2.0@global/gems/iruby-0.2.7/bin/iruby:5:in `<top (required)>'
/Users/yosriady/.rvm/rubies/ruby-2.2.0/bin/iruby:23:in `load'
/Users/yosriady/.rvm/rubies/ruby-2.2.0/bin/iruby:23:in `<main>'
/Users/yosriady/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/yosriady/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

Any ideas? I also tried requiring `gnuplot` in my Ruby notebooks, and it fails.
```
LoadError: cannot load such file -- gnuplot
```

**Comment by v0dro** [comment]
If you're using OSX this might be related to #40

**Comment by minad** [comment]
This is just a warning, not an error. iruby should work normally afterwards.

**Comment by Ryuutei** [comment]
I have the same warning. iruby installed perfectly, dependencies too.
Although the console loads without that warning when `iruby` or `jupyter-console --kernel=ruby` are launched in the jupyter kernel folder or the iruby source folder.

Is there a way to set iruby to tell bundler to check in those folders instead of the folder where the command is executed ? 

Thanks.

**Comment by brodock** [comment]
@Ryuutei it's possible, when using bundler pass: `--gemfile=path/to/Gemfile`
