### ISSUE TITLE
[OSX] malloc error incorrect checksum for freed object

### ISSUE THREAD

**Issue by devster31** [SciRuby/iruby#54]
I've got a case of this:
```
❯ jupyter qtconsole --kernel=ruby
W, [2015-12-16T18:04:53.245480 #44379]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:198:in `rescue in root'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:194:in `root'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:101:in `bundle_path'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:435:in `configure_gem_home'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:427:in `configure_gem_home_and_path'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:92:in `configure'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:153:in `definition'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/usr/local/var/rbenv/versions/2.2.0/bin/iruby:23:in `load'
/usr/local/var/rbenv/versions/2.2.0/bin/iruby:23:in `<main>'
ruby(44379,0x7fff7882d300) malloc: *** error for object 0x7f8b2e2b2528: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[JupyterQtConsoleApp] KernelRestarter: restarting kernel (1/5)
[JupyterQtConsoleApp] WARNING | kernel restarted
W, [2015-12-16T18:04:55.928800 #44385]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:198:in `rescue in root'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:194:in `root'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:101:in `bundle_path'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:435:in `configure_gem_home'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:427:in `configure_gem_home_and_path'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:92:in `configure'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:153:in `definition'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/usr/local/var/rbenv/versions/2.2.0/bin/iruby:23:in `load'
/usr/local/var/rbenv/versions/2.2.0/bin/iruby:23:in `<main>'
ruby(44385,0x7fff7882d300) malloc: *** error for object 0x7f8085d3c398: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

The error keeps respawning unless I Ctrl-C or close the qtconsole. And the similar:
```
❯ jupyter console --kernel=ruby
W, [2015-12-16T18:10:25.110421 #44674]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:198:in `rescue in root'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:194:in `root'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:101:in `bundle_path'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:435:in `configure_gem_home'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:427:in `configure_gem_home_and_path'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:92:in `configure'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler.rb:153:in `definition'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/usr/local/var/rbenv/versions/2.2.0/bin/iruby:23:in `load'
/usr/local/var/rbenv/versions/2.2.0/bin/iruby:23:in `<main>'
ruby(44674,0x7fff7882d300) malloc: *** error for object 0x7f904305a508: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Jupyter Console 4.0.3

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic
```

Which hangs until I force TERM the process.
Ruby version is:
```
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
```
I'm on OSX Yosemite 10.10.5, I installed jupyter in a pyenv something like
```sh
pyenv virtualenv 3.5 jupyter
pyenv activate jupyter
pip install jupyter
```

My kernels are:
```
  ruby       /Users/<user>/.ipython/kernels/ruby
  python3    /usr/local/var/pyenv/versions/jupyter/lib/python3.5/site-packages/ipykernel/resources
  ir         /usr/local/share/jupyter/kernels/ir
```
and they seem to work except the ruby one.

**Comment by acrogenesis** [comment]
switching to iruby 0.2.7 solved it for me

**Comment by devster31** [comment]
True, 0.2.7 works, but there's a pretty big change from 0.2.7 and that's:
```ruby
Gem::Specification.new do |s|
    ...
    s.add_runtime_dependency 'rbczmq', '~> 1.7'
    ...
end
```
which means that something broke in the update.

**Comment by domitry** [comment]
Can you try `gem list | grep 'rbczmq'` and `gem list | grep 'ffi-rzmq'`?

**Comment by devster31** [comment]
```sh
rbczmq (1.7.9)
ffi-rzmq (2.0.4)
ffi-rzmq-core (1.0.4)
```
I repeated the installation process in a clean environment, `rcbzmq` was installed when I downgraded to 0.2.7, `ffi-rzmq` is installed in the newer version instead.

**Comment by domitry** [comment]
The dependent library of ffi-rzmq is not installed correctly, I think. (e.g. the version is too newer of older)

If so or not, iruby v0.2.8 is compatible with rbczmq and do not dependent on ffi-rzmq, so just uninstall ffi-rzmq and bump up iruby to 0.2.8 and it will work.

**Comment by devster31** [comment]
That fixed it, thanks, you can close this issue. There's still some problems with the qtconsole but the terminal console and notebook work fine.

**Comment by domitry** [comment]
:+1:
