### ISSUE TITLE
ZMQ::Error when running parallel's multi process with :progress option

### ISSUE THREAD

**Issue by sudodo** [SciRuby/iruby#71]
ZMQ::Error occurs when I execute the following code on Jupyter notebook:

```
Parallel.each([1,2,3], in_process: 3, :progress => "Doing stuff") do |x|
  x
end
```

The error does not occur on irb. Only Jupyter notebook raises the error.

My environment is
- Mac OSX 10.8
- ipython 3.0.0
- iruby 0.2.8 (0.2.7?)
- parallel 1.6.1
- rbczmq 1.7.9

The error message is 

```
ZMQ::Error: Cross thread violation for PUB socket 0x007fe907085f00: created in thread 0x007fe9028cb7c8, invoked on thread 0x007fe9061e4ac8
/Users/myname/.rvm/gems/ruby-2.1.5/gems/iruby-0.2.8/lib/iruby/session/rbczmq.rb:50:in `send_message'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/iruby-0.2.8/lib/iruby/session/rbczmq.rb:50:in `send'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/iruby-0.2.8/lib/iruby/ostream.rb:30:in `write'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:51:in `print_and_flush'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:46:in `block in refresh'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/throttle.rb:22:in `choke'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:43:in `refresh'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:39:in `with_refresh'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/base.rb:155:in `update_progress'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/base.rb:95:in `increment'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:260:in `block in add_progress_bar!'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:422:in `call'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:422:in `block in with_instrumentation'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:422:in `synchronize'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:422:in `with_instrumentation'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:318:in `block (3 levels) in work_in_processes'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:312:in `loop'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:312:in `block (2 levels) in work_in_processes'
/Users/myname/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:183:in `block (2 levels) in in_threads'
```

**Comment by kojix2** [comment]
Yes. Parallel gems are very important.

A few months ago I checked that the Parallel gem does not work.
A similar error occurred.

But today, I found it work.
I don't know why.

Very nice.

![file](https://user-images.githubusercontent.com/5798442/57343564-cf584f80-717e-11e9-9986-7563571be233.gif)

@sudodo please check it.
(I will close this issue when a new version of IRuby is released.)

**Comment by kojix2** [comment]
Umm `Parallel.map` does not work in some environment.

**Comment by sudodo** [comment]
@kojix2 Thank you! Your code in the animation works well in my environment.
