### ISSUE TITLE
Kernel died: uninitialized constant IRuby::Kernel::Session

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/iruby#74]
I'm getting the following error:

```
[I 13:40:54.644 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 13:40:54.676 NotebookApp] Serving notebooks from local directory: /Users/jwoods/Projects/batch
[I 13:40:54.676 NotebookApp] 0 active kernels
[I 13:40:54.676 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 13:40:54.676 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 13:40:59.062 NotebookApp] Kernel started: 46813283-26ec-47cd-9a04-1d41b57214fb
You should install rbczmq or ffi_rzmq before running iruby notebook. See README.
F, [2016-03-16T13:40:59.388306 #70696] FATAL -- : Kernel died: uninitialized constant IRuby::Kernel::Session
/Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize'
/Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
/Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
/Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/Users/jwoods/.rbenv/versions/2.2.2/bin/iruby:23:in `load'
/Users/jwoods/.rbenv/versions/2.2.2/bin/iruby:23:in `<main>'
/Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize': uninitialized constant IRuby::Kernel::Session (NameError)
	from /Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
	from /Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
	from /Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
	from /Users/jwoods/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
	from /Users/jwoods/.rbenv/versions/2.2.2/bin/iruby:23:in `load'
	from /Users/jwoods/.rbenv/versions/2.2.2/bin/iruby:23:in `<main>'
```

I'm using rbczmq version 1.7.9, Ruby 2.2.2p95, iruby 0.2.8.

**Comment by mohawkjohn** [comment]
Found the solution. I'm in a project with its own Gemfile, and I had to add not only iruby but also rbczmq to the list of gems. (In my case, that meant my gemspec. In others, it might mean you add it directly to the Gemfile).

**Comment by kylekyle** [comment]
Also, I warnings about a missing Gemfile everytime I start a IRuby. Would someone mind sharing the backstory for why we load Gemfiles automatically?

**Comment by kojix2** [comment]
Related issue
#144
